### ISSUE TITLE
Unicode Decode Error when accessing /settings

### ISSUE THREAD

**Issue by sarabveer** [StyraHem/pyShelly#21]
```
Error http GET: http://10.0.0.14/settings, 'charmap' codec can't decode byte 0x81 in position 203: character maps to <undefined>, Traceback (most recent call last): File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 62, in shelly_http_get res = json.loads(s(body)) File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s return str(x, 'cp1252') File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode return codecs.charmap_decode(input,errors,decoding_table) UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 203: character maps to <undefined>
```

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pyShelly/utils.py", line 62, in shelly_http_get
    res = json.loads(s(body))
  File "/usr/local/lib/python3.7/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.7/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 203: character maps to <undefined>
```

**Comment by chemelli74** [comment]
Device ?

**Comment by sarabveer** [comment]
@chemelli74 Sorry, should have included that.

I have three Shelly 1's all on firmware `20200601-122823/v1.7.0@d7961837`.

This does not affect the functionality, it just spams the the error logs.

**Comment by chemelli74** [comment]
If you have access to your HA via SSH, I can guide you to a small change to allow more debugging.

Simone

**Comment by hakana** [comment]
I think this issue is fixed, please let me know if not.
