### ISSUE TITLE
exception when loading shelly device in HA

### ISSUE THREAD

**Issue by rafiw** [StyraHem/pyShelly#51]
the url contains hebrew charecters 
`[{"name":"עמודים פנים","ison":false,"has_timer":false,`
2020-11-27 16:09:34 ERROR (CoAP) [pyShelly] Error http GET: http://192.168.0.105/settings, 'charmap' codec can't decode byte 0x9d in position 1700: character maps to <undefined>, Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/utils.py", line 63, in shelly_http_get
    res = json.loads(s(body))
  File "/usr/local/lib/python3.8/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.8/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1700: character maps to <undefined>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyShelly/utils.py", line 63, in shelly_http_get
    res = json.loads(s(body))
  File "/usr/local/lib/python3.8/site-packages/pyShelly/compat.py", line 23, in s
    return str(x, 'cp1252')
  File "/usr/local/lib/python3.8/encodings/cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1700: character maps to <undefined>

**Comment by hakana** [comment]
What is the name of the device?

**Comment by rafiw** [comment]
עמודים פנים

**Comment by hakana** [comment]
I tried to set the name to the same and for me, it working. Do you still have this problem?

**Comment by hakana** [comment]
![image](https://user-images.githubusercontent.com/1168654/103412761-fdba4800-4b76-11eb-9c65-06c1f93d8477.png)
