### ISSUE TITLE
[pyShelly] Can't setup CoAP listener

### ISSUE THREAD

**Issue by kongo09** [StyraHem/pyShelly#65]
I just did a restore of a full Home Assistant backup after my system had crashed. Complete fresh install on a Raspberry Pi 4. Now I get the following error:

`2021-09-02 22:40:49 ERROR (MainThread) [pyShelly] Can't setup CoAP listener`

I'm running ShellyForHass 0.2.2

**Comment by kongo09** [comment]
Some more context from the logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyShelly/coap.py", line 28, in start
    self._init_socket()
  File "/usr/local/lib/python3.9/site-packages/pyShelly/coap.py", line 53, in _init_socket
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device
```

What does `No such device` mean?

**Comment by kongo09** [comment]
Hm, I guess I solved this myself. I have a VLAN configured and use the `configuration.yaml` for the settings. When I did the full restore on a fresh device, the IP of the VLAN with my Shelly devices changed, so the configuration didn't match anymore, so the `host_ip` was not correct.

Fixing the `host_ip` to the new value and restarting HomeAssistant solved this problem. I'll close this now.
